import { createClient } from 'npm:@supabase/supabase-js@2.57.4';
import { carve, fixture, groundTruth, sha, canonical, pdfReport, MAX, signatures } from './engines.ts';
const URL=Deno.env.get('SUPABASE_URL')!;
const service=createClient(URL,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false,autoRefreshToken:false}});
const bucket='retrace-evidence', reportBucket='retrace-reports';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, apikey, content-type, x-client-info','Access-Control-Allow-Methods':'GET, POST, OPTIONS','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'};
class Problem extends Error {constructor(public status:number,message:string){super(message)}}
const fail=(status:number,message:string):never=>{throw new Problem(status,message)};
async function db(q:any){const {data,error}=await q;if(error)throw new Problem(422,error.message);return data}
function json(value:any,status=200){return new Response(JSON.stringify(value),{status,headers:{...cors,'Content-Type':'application/json'}})}
const clean=(s:any,n=200)=>String(s??'').slice(0,n);
function requireRole(actor:any,admin=false){if(admin?actor.role!=='ADMIN':!['ADMIN','INVESTIGATOR'].includes(actor.role))fail(403,admin?'Administrator required':'Read-only role')}
async function access(cid:string,actor:any,write=false){if(write)requireRole(actor);const c=await db(service.from('cases').select('*').eq('id',cid).maybeSingle());if(!c)fail(404,'Case not found');if(c.owner===actor.id||actor.role==='ADMIN')return c;const m=await db(service.from('case_members').select('case_id').eq('case_id',cid).eq('user_id',actor.id).maybeSingle());if(!m)fail(404,'Case not found');return c}
async function event(actor:any,action:string,cid:string|null=null,details:any={}){return db(service.rpc('retrace_append_event',{actor_id:actor.id,action_name:action,cid,event_details:details,sid:actor.session_id}))}
async function timeline(cid:string|null){
 const load=async(q:any)=>{const rows:any[]=[];for(let start=0;start<10000;start+=500){const page=await db(q.range(start,start+499));rows.push(...page);if(page.length<500)return rows}fail(413,'Timeline exceeds current 10,000-event export limit')};
 let q=service.from('audit_events').select('*').order('sequence');q=cid?q.eq('case_id',cid):q.is('case_id',null);const rows=await load(q);
 const sessions=[...new Set(rows.map((r:any)=>r.body.session_id).filter(Boolean))];
 const identity=cid&&sessions.length?await load(service.from('audit_events').select('*').is('case_id',null).in('body->>session_id',sessions).in('body->>action',['SESSION_STARTED','SESSION_ENDED','ALL_SESSIONS_REVOKED']).order('sequence')):[];
 return [...rows,...identity].map((r:any)=>({...r.body,sequence:r.sequence,hash:r.hash,previous_hash:r.previous_hash,canonical_payload:r.canonical_payload,chain_scope:r.case_id?'case':'identity'})).sort((a:any,b:any)=>new Date(a.timestamp).getTime()-new Date(b.timestamp).getTime()||a.sequence-b.sequence)
}
async function detail(cid:string,actor:any){const c=await access(cid,actor);const [sources,jobs,evidence,reports,events]=await Promise.all([db(service.from('evidence_sources').select('*').eq('case_id',cid).order('created')),db(service.from('jobs').select('*').eq('case_id',cid).order('created',{ascending:false})),db(service.from('recovered_files').select('*').eq('case_id',cid)),db(service.from('reports').select('id,created,pdf_hash').eq('case_id',cid).order('created',{ascending:false})),timeline(cid)]);return {case:c,sources,jobs,evidence,reports,events}}
async function saveBlob(path:string,data:Uint8Array,b= bucket,upsert=false){const{error}=await service.storage.from(b).upload(path,data,{contentType:'application/octet-stream',upsert});if(error)throw Error(error.message)}
async function getBlob(path:string,b=bucket){const{data,error}=await service.storage.from(b).download(path);if(error||!data)throw Error('Stored artifact unavailable');return new Uint8Array(await data.arrayBuffer())}
async function removeBlob(path:string,b=bucket){const{error}=await service.storage.from(b).remove([path]);if(error)throw Error(error.message)}
async function addSource(cid:string,actor:any,data:Uint8Array,name:string,media:string,kind:string){if(!data.length||data.length>MAX)fail(413,'Cloud source must contain 1 byte to 8 MiB');const existing=await db(service.from('evidence_sources').select('size').eq('case_id',cid));if(existing.reduce((n:number,r:any)=>n+r.size,0)+data.length>64*1024*1024)fail(413,'64 MiB per-case source quota reached');const id=crypto.randomUUID(),path=cid+'/sources/'+id;await saveBlob(path,data);try{const r=await db(service.from('evidence_sources').insert({id,case_id:cid,name,media,kind,size:data.length,hash:await sha(data),storage_path:path}).select().single());await event(actor,'SOURCE_INSPECTED',cid,{source_id:id,name,media,kind,size:data.length,sha256:r.hash,media_detection:'Operator-declared; native hardware not connected'});return r}catch(e){await removeBlob(path);throw e}}
function policy(s:any,b:any){return {media:s.media,media_basis:'Operator-declared profile',scope:b.module,purpose:b.purpose||'Internal reuse',sensitivity:b.sensitivity||'Normal',sandbox_method:'Storage working-copy zero overwrite, full logical read-back and residual scan',native_recommendation:s.media==='SSD'?'ATA sanitize / controller-supported crypto erase':s.media==='NVMe'?'NVMe sanitize / crypto erase':'Media-specific native capability assessment',native_available:false,decision:b.purpose&&b.purpose!=='Internal reuse'||b.sensitivity==='Highly sensitive'?'Escalate to native purge/destroy assessment':'Logical working-copy clear demonstration',standards:['NIST SP 800-88 Rev.2 guidance reference','IEEE 2883 future native method assessment'],limitations:'Not certified. Original uploads remain. Cloud object overwrite cannot guarantee physical erasure of provider disks, snapshots or backups.'}}
async function overwrite(data:Uint8Array,path:string,unlink:boolean){const begin=performance.now();const before=await sha(data);await saveBlob(path,data);try{await saveBlob(path,new Uint8Array(data.length),bucket,true);const readback=await getBlob(path);const verified=readback.length===data.length&&readback.every(x=>x===0);const scan=await carve(readback);await removeBlob(path);const probe=await service.storage.from(bucket).download(path);return {before_sha256:before,after_sha256:await sha(readback),bytes_processed:data.length,duration_seconds:(performance.now()-begin)/1000,readback_verified:verified,absence_verified:!!probe.error,validation:scan.files.length?'WARNING':scan.complete?'PASS':'INCONCLUSIVE',residual_artifacts:scan.files.length,method:'Cloud object working-copy zero overwrite and logical read-back',metadata:{work_copy_name_removed:true,scope:'Cloud working-object removal only. No OS journal, snapshot, backup, original-source or provider-media cleansing.'},assurance:'Logical sandbox verification; not physical-media sanitization'}}catch(e){await removeBlob(path).catch(()=>{});throw e}}
async function runJob(cid:string,actor:any,b:any){if(!['drive','files','recovery','validation'].includes(b.module))fail(400,'Invalid module');if(!Array.isArray(b.source_ids)||!b.source_ids.length||b.source_ids.length>10)fail(400,'Select 1 to 10 sources');const ids=[...new Set(b.source_ids)];const sources=await db(service.from('evidence_sources').select('*').eq('case_id',cid).in('id',ids));if(sources.length!==ids.length)fail(404,'Source not found in this case');if(sources.reduce((n:number,s:any)=>n+s.size,0)>MAX)fail(413,'Cloud batch total must be at most 8 MiB');if(['drive','files'].includes(b.module)&&b.confirmation!=='ERASE SANDBOX COPY')fail(400,'Type ERASE SANDBOX COPY');if(b.module==='drive'&&(sources.length!==1||sources[0].kind!=='image'))fail(400,'Select one raw image');if(b.module==='files'&&sources.some((s:any)=>s.kind!=='file'))fail(400,'Select file targets');const types=b.types??Object.keys(signatures);if(!types.length||types.some((t:string)=>!signatures[t]))fail(400,'Invalid recovery types');const recent=await db(service.from('jobs').select('id').eq('actor',actor.id).gte('created',new Date(Date.now()-60000).toISOString()));if(recent.length>=6)fail(429,'Wait one minute before starting more jobs');const jid=crypto.randomUUID();await db(service.from('jobs').insert({id:jid,case_id:cid,actor:actor.id,module:b.module,status:'RUNNING'}));await event(actor,'JOB_STARTED',cid,{job_id:jid,module:b.module,source_ids:ids});const begin=performance.now();const result:any={items:[],bytes_processed:0,scope:'Cloud sandbox working copies; original sources retained'};
try{for(const s of sources){const original=await getBlob(s.storage_path);if(await sha(original)!==s.hash)throw Error('Source integrity mismatch');result.bytes_processed+=original.length;let item:any;if(['drive','files'].includes(b.module)){item=await overwrite(original,cid+'/work/'+jid+'/'+s.id,b.module==='files');item.policy=policy(s,b)}else{const scan=await carve(original,types);const recovered=[];for(const hit of scan.files){const blob=hit.data;delete hit.data;hit.id=crypto.randomUUID();if(b.module==='recovery'){const path=cid+'/recovered/'+jid+'/'+hit.id;await saveBlob(path,blob);await db(service.from('recovered_files').insert({id:hit.id,case_id:cid,job_id:jid,storage_path:path,details:hit}));await event(actor,'FILE_RECOVERED',cid,{job_id:jid,source_id:s.id,...hit})}recovered.push(hit)}item={...scan,ground_truth:await groundTruth(original,recovered),files:recovered,validation:recovered.length?'WARNING':scan.complete?'PASS':'INCONCLUSIVE',validation_scope:'Supported contiguous formats only; absence is not proof of total erasure'}}item.source_id=s.id;item.source_unchanged=await sha(await getBlob(s.storage_path))===s.hash;if(!item.source_unchanged)throw Error('Original source changed during operation');result.items.push(item)}result.duration_seconds=(performance.now()-begin)/1000;result.throughput_mib_s=result.bytes_processed/1048576/Math.max(result.duration_seconds,1e-6);await db(service.from('jobs').update({status:'COMPLETED',result}).eq('id',jid));await event(actor,'JOB_COMPLETED',cid,{job_id:jid,module:b.module,...result});return{id:jid,status:'COMPLETED',result}}catch(e){result.error=String(e).slice(0,300);await db(service.from('jobs').update({status:'FAILED',result}).eq('id',jid));await event(actor,'JOB_FAILED',cid,{job_id:jid,error:result.error});fail(422,result.error)}}
const base64=(b:Uint8Array)=>btoa(String.fromCharCode(...b));
const unbase64=(s:string)=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
async function signingKey(){let stored=await db(service.rpc('retrace_signing_key'));if(!stored){const pair=await crypto.subtle.generateKey({name:'Ed25519'},true,['sign','verify']);await db(service.rpc('retrace_set_signing_key',{priv:await crypto.subtle.exportKey('jwk',pair.privateKey),pub:await crypto.subtle.exportKey('jwk',pair.publicKey)}));stored=await db(service.rpc('retrace_signing_key'))}return stored}
async function verifyEnvelope(v:any){try{const key=await crypto.subtle.importKey('raw',unbase64(v.public_key),{name:'Ed25519'},false,['verify']);return await crypto.subtle.verify('Ed25519',key,unbase64(v.signature),new TextEncoder().encode(canonical(v.payload)))}catch{return false}}
async function report(cid:string,actor:any){const d=await detail(cid,actor),id=crypto.randomUUID();const payload:any={id,case:d.case,operator:actor,created:new Date().toISOString(),scope:'Cloud sandbox demonstrator; not a certified sanitization certificate. Original evidence retained.',sources:d.sources,jobs:d.jobs,evidence:d.evidence,timeline:d.events,audit:await db(service.rpc('retrace_verify_audit',{cid}))};const pdf=await pdfReport(payload);payload.pdf_sha256=await sha(pdf);const k=await signingKey(),key=await crypto.subtle.importKey('jwk',k.private_jwk,{name:'Ed25519'},false,['sign']),pub=await crypto.subtle.importKey('jwk',k.public_jwk,{name:'Ed25519'},true,['verify']);const publicBytes=new Uint8Array(await crypto.subtle.exportKey('raw',pub));const envelope={payload,algorithm:'Ed25519',canonicalization:'recursive-key-sort-json',signature:base64(new Uint8Array(await crypto.subtle.sign('Ed25519',key,new TextEncoder().encode(canonical(payload))))),public_key:base64(publicBytes),key_fingerprint:await sha(publicBytes)};const path=cid+'/'+id+'.pdf';await saveBlob(path,pdf,reportBucket);await db(service.from('reports').insert({id,case_id:cid,envelope,pdf_hash:payload.pdf_sha256,storage_path:path}));await event(actor,'REPORT_GENERATED',cid,{report_id:id,pdf_sha256:payload.pdf_sha256,key_fingerprint:envelope.key_fingerprint});return{id,key_fingerprint:envelope.key_fingerprint}}
async function benchmark(cid:string,actor:any){const id=crypto.randomUUID(),begin=performance.now(),{data,payloads}=await fixture();const scan=await carve(data),expected=await Promise.all(payloads.map(sha));const bad=data.slice(),offset=data.findIndex((_,i)=>data[i]===137&&data[i+1]===80);bad[offset+20]^=1;const damaged=await carve(bad,['png']);const cleared=await overwrite(data,cid+'/work/benchmark-'+id,true);const result:any={fixture:'Eight artifacts across four formats embedded in raw bytes without filesystem metadata',bytes_processed:data.length,checks:{eight_artifacts_recovered:scan.files.length===8,hashes_match_ground_truth:scan.files.every((f:any)=>expected.includes(f.sha256))&&scan.files.length===expected.length,malformed_png_rejected:damaged.files.length===1&&damaged.rejected.some((r:any)=>r.offset===offset),readback_zeroed:cleared.readback_verified,post_erase_no_supported_artifacts:cleared.validation==='PASS',working_copy_removed:cleared.absence_verified},duration_seconds:(performance.now()-begin)/1000,limits:'Small synthetic contiguous-file fixture; not independent certification'};result.ground_truth=await groundTruth(data,scan.files);result.passed=Object.values(result.checks).every(Boolean);result.throughput_mib_s=data.length/1048576/result.duration_seconds;await db(service.from('jobs').insert({id,case_id:cid,actor:actor.id,module:'benchmark',status:'COMPLETED',result}));await event(actor,'VALIDATION_BENCHMARK_COMPLETED',cid,{job_id:id,...result});return result}

Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response(null,{headers:cors});try{const path=new globalThis.URL(req.url).pathname.replace(/^.*\/retrace-api/,'')||'/';if(path==='/health')return json({status:'ok',version:'0.2.0',auth_mode:'supabase',mode:'cloud-sandbox',database:'Supabase PostgreSQL',max_source_bytes:MAX});if(!['GET','POST'].includes(req.method))fail(405,'Method not allowed');const token=req.headers.get('Authorization')?.replace(/^Bearer\s+/i,'');if(!token)fail(401,'Sign in required');const{data:ud,error:ue}=await service.auth.getUser(token);if(ue||!ud.user)fail(401,'Session expired or invalid');if(!ud.user.email_confirmed_at)fail(403,'Verify your email before using Re-Trace');const userClient=createClient(URL,Deno.env.get('SUPABASE_ANON_KEY')!,{global:{headers:{Authorization:'Bearer '+token}},auth:{persistSession:false,autoRefreshToken:false}});if(!await db(userClient.rpc('retrace_session_active')))fail(401,'Session revoked');const p=await db(service.from('profiles').select('*').eq('id',ud.user.id).single());const claims=JSON.parse(new TextDecoder().decode(Uint8Array.from(atob(token.split('.')[1].replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0))));const actor={id:p.id,email:p.email,role:p.role,session_id:claims.session_id};const post=req.method==='POST';const body=post&&!req.headers.get('content-type')?.includes('multipart/form-data')?await req.json().catch(()=>({})):{};
if(path==='/auth/password-updated'&&post){await event(actor,'PASSWORD_UPDATED');return json({recorded:true})}
if(path==='/auth/me')return json(actor);
if(path==='/auth/supabase'&&post){await event(actor,'SESSION_STARTED',null,{method:'Supabase verified-email session'});return json({token,user:actor,expires_in:Math.max(0,claims.exp-Math.floor(Date.now()/1000))})}
if(['/auth/logout','/auth/revoke-all'].includes(path)&&post){await event(actor,path.endsWith('revoke-all')?'ALL_SESSIONS_REVOKED':'SESSION_ENDED');const{error}=await service.auth.admin.signOut(token,path.endsWith('revoke-all')?'global':'local');if(error)throw error;return json({revoked:true})}
if(path==='/users'){requireRole(actor,true);return json(await db(service.from('profiles').select('*')))}
let m=path.match(/^\/users\/([^/]+)\/role$/);if(m&&post){requireRole(actor,true);if(m[1]===actor.id||!['ADMIN','INVESTIGATOR','VIEWER'].includes(body.role))fail(400,'Invalid role change');await db(service.from('profiles').update({role:body.role}).eq('id',m[1]));await event(actor,'ROLE_CHANGED',null,{user_id:m[1],role:body.role});return json({updated:true})}
if(path==='/security-events'){requireRole(actor,true);return json(await timeline(null))}
if(path==='/cases'){if(post){requireRole(actor);const title=clean(body.title,160);if(title.length<3)fail(400,'Title requires at least 3 characters');const c=await db(service.from('cases').insert({title,description:clean(body.description,3000),owner:actor.id}).select().single());await event(actor,'CASE_CREATED',c.id,{title});return json(c)}return json(await db(userClient.from('cases').select('*').order('created',{ascending:false})))}
m=path.match(/^\/cases\/([^/]+)(?:\/(.*))?$/);if(m){const cid=m[1],action=m[2]||'';await access(cid,actor,post&&!['open','audit/verify'].includes(action));if(!action&&!post)return json(await detail(cid,actor));if(action==='open'&&post){await event(actor,'CASE_OPENED',cid);return json({opened:true})}if(action==='members'&&post){requireRole(actor,true);await db(service.from('case_members').upsert({case_id:cid,user_id:body.user_id}));await event(actor,'CASE_MEMBER_ADDED',cid,{user_id:body.user_id});return json({added:true})}
if(action==='sources'&&post){const length=Number(req.headers.get('content-length')||0);if(length>MAX+1024*1024)fail(413,'Upload exceeds cloud limit');const form=await req.formData(),file=form.get('file');if(!(file instanceof File))fail(400,'File required');if(file.size>MAX)fail(413,'Cloud source limit is 8 MiB');const kind=String(form.get('kind')||'image'),media=String(form.get('media')||'Image');if(!['image','file'].includes(kind)||!['HDD','SSD','NVMe','USB','SD','Optical','Image'].includes(media))fail(400,'Invalid source type');const name=clean(file.name.replaceAll('\\','/').split('/').pop());if(kind==='image'&&!/\.(img|raw|dd|bin)$/i.test(name))fail(400,'Raw image extensions: .img .raw .dd .bin');return json(await addSource(cid,actor,new Uint8Array(await file.arrayBuffer()),name,media,kind))}
if(action==='demo-source'&&post){const{data}=await fixture();return json(await addSource(cid,actor,data,'four-format-forensic-fixture.img','USB','image'))}
if(action==='policy'&&post){if(!Array.isArray(body.source_ids)||!body.source_ids.length)fail(400,'Select sources');const s=await db(service.from('evidence_sources').select('*').eq('case_id',cid).in('id',body.source_ids));if(s.length!==new Set(body.source_ids).size)fail(404,'Source not found');const result=s.map((v:any)=>policy(v,body));await event(actor,'POLICY_GENERATED',cid,{policies:result});return json(result)}
if(action==='jobs'&&post)return json(await runJob(cid,actor,body));
if(action==='benchmark'&&post)return json(await benchmark(cid,actor));
if(action==='timeline')return json(await timeline(cid));
if(action==='audit/verify'&&post){const result=await db(service.rpc('retrace_verify_audit',{cid}));await event(actor,'AUDIT_VERIFIED',cid,result);return json(result)}
if(action==='audit/tamper-demo'&&post){requireRole(actor,true);const rows=await timeline(cid);if(!rows.length)fail(400,'No events');const copy=structuredClone(rows.find((r:any)=>r.case_id===cid));copy.action='MODIFIED_COPY_ONLY';const modified={...copy};for(const k of ['sequence','previous_hash','hash','canonical_payload','chain_scope'])delete modified[k];const changed=canonical(modified)!==canonical(JSON.parse(copy.canonical_payload));const result={copy_result:{status:changed?'BROKEN':'VALID',first_invalid_event:copy.id},primary_result:await db(service.rpc('retrace_verify_audit',{cid}))};await event(actor,'TAMPER_DEMO_ON_COPY',cid,result);return json(result)}
if(action==='reports'&&post)return json(await report(cid,actor));}
if(path==='/reports/verify-signature'&&post)return json({status:await verifyEnvelope(body)?'VALID':'BROKEN',trust:'Compare the signing-key fingerprint with an independently saved value'});
m=path.match(/^\/evidence\/([^/]+)\/download$/);if(m){const r=await db(service.from('recovered_files').select('*').eq('id',m[1]).maybeSingle());if(!r)fail(404,'Evidence not found');await access(r.case_id,actor);const data=await getBlob(r.storage_path);if(await sha(data)!==r.details.sha256)fail(409,'Evidence hash mismatch');await event(actor,'EVIDENCE_DOWNLOADED',r.case_id,{evidence_id:r.id,sha256:r.details.sha256});return new Response(data,{headers:{...cors,'Content-Type':'application/octet-stream','Content-Disposition':`attachment; filename="recovered-${r.id}.${r.details.type}"`}})}
m=path.match(/^\/reports\/([^/]+)\/(json|pdf)$/);if(m){const r=await db(service.from('reports').select('*').eq('id',m[1]).maybeSingle());if(!r)fail(404,'Report not found');await access(r.case_id,actor);if(!await verifyEnvelope(r.envelope))fail(409,'Report signature invalid');await event(actor,'REPORT_DOWNLOADED',r.case_id,{report_id:r.id,format:m[2]});if(m[2]==='json')return new Response(JSON.stringify(r.envelope),{headers:{...cors,'Content-Type':'application/json','Content-Disposition':`attachment; filename="retrace-${r.id}.json"`}});const bytes=await getBlob(r.storage_path,reportBucket);if(await sha(bytes)!==r.pdf_hash)fail(409,'PDF hash mismatch');return new Response(bytes,{headers:{...cors,'Content-Type':'application/pdf','Content-Disposition':`attachment; filename="retrace-${r.id}.pdf"`}})}
fail(404,'Endpoint not found');}catch(e){console.error(e instanceof Problem?e.message:'Re-Trace operation failed');return json({detail:e instanceof Problem?e.message:String(e).slice(0,240)},e instanceof Problem?e.status:500)}});
